# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            土豆帮
#tagline:          'A Jekyll theme'
description:      'A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content. Made by @mdo.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           '土豆帮'
  url:            http://my.oschina.net/tudoubang/blog

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tudoubang

#Time
timezone:         Asia/Shanghai

